server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: donate
          uri: http://localhost:8082
          predicates:
            - Path=/donates/**, 
        - id: request
          uri: http://localhost:8083
          predicates:
            - Path=/requests/**, 
        - id: bookdetail
          uri: http://localhost:8084
          predicates:
            #- Path=,
            - Path=/bookdetails, 
        - id: books
          uri: http://localhost:8085
          predicates:
            - Path=/books/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: donate
          uri: http://donate:8080
          predicates:
            - Path=/donates/**, 
        - id: request
          uri: http://request:8080
          predicates:
            - Path=/requests/**, 
        - id: bookdetail
          uri: http://bookdetail:8080
          predicates:
            - Path=/bookdetails, 
        - id: books
          uri: http://books:8080
          predicates:
            - Path=/books/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
