---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: donate
  labels:
    app: donate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donate
  template:
    metadata:
      labels:
        app: donate
    spec:
      containers:
        - name: donate
          image: username/donate:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: request
  labels:
    app: request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request
  template:
    metadata:
      labels:
        app: request
    spec:
      containers:
        - name: request
          image: username/request:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookdetail
  labels:
    app: bookdetail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookdetail
  template:
    metadata:
      labels:
        app: bookdetail
    spec:
      containers:
        - name: bookdetail
          image: username/bookdetail:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: username/books:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: donate
  labels:
    app: donate
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: donate


---


apiVersion: v1
kind: Service
metadata:
  name: request
  labels:
    app: request
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: request


---


apiVersion: v1
kind: Service
metadata:
  name: bookdetail
  labels:
    app: bookdetail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookdetail


---


apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    app: books
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: books

