apiVersion: apps/v1
kind: Deployment
metadata:
  name: request
  labels:
    app: request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request
  template:
    metadata:
      labels:
        app: request
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: request
          image: "drsuneamerr/request:v1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/mnt/data"
              name: volume
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile 
